name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Явно устанавливаем стабильный Python 3.11 на сам сервер GitHub
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Ставим системные пакеты Linux, которые нужны для сборки Android приложений
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev libssl-dev build-essential ccache git python3-dev openjdk-17-jdk unzip zip
          pip install --upgrade pip setuptools wheel
          pip install buildozer==1.5.0 cython==0.29.36

      # Запускаем сборку напрямую, в обход чужих кастомных экшенов
      - name: Build Android APK
        run: |
          export ALLOW_ROOT=1
          export APP_ALLOW_ROOT=1
          yes y | buildozer android debug


      # Сохраняем готовый файл
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: program-apk
          path: bin/*.apk
